-- Obit Cooperative PostgreSQL financial target schema
-- Integer kobo fields are authoritative for all money.

CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT UNIQUE, phone TEXT UNIQUE,
 password_hash TEXT, role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('member','staff','admin')),
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED','CLOSED')),
 session_version INTEGER NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS member_applications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id), full_legal_name TEXT,
 date_of_birth TEXT, gender TEXT, phone TEXT, whatsapp TEXT, email TEXT, address TEXT, state TEXT, lga TEXT,
 occupation_category TEXT, membership_type TEXT, application_date TIMESTAMPTZ NOT NULL DEFAULT now(),
 next_of_kin_name TEXT, next_of_kin_phone TEXT, intended_savings_amount NUMERIC(18,2),
 intended_savings_frequency TEXT, interests_json TEXT, referral_source TEXT, campaign TEXT,
 status TEXT NOT NULL DEFAULT 'LEAD', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS members (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL UNIQUE REFERENCES member_applications(id),
 user_id BIGINT REFERENCES users(id), member_code TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'ACTIVE',
 activated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ledger_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 account_type TEXT NOT NULL DEFAULT 'SAVINGS', balance NUMERIC(18,2) NOT NULL DEFAULT 0,
 balance_kobo BIGINT NOT NULL DEFAULT 0 CHECK(balance_kobo>=0), currency TEXT NOT NULL DEFAULT 'NGN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id), type TEXT NOT NULL,
 amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT NOT NULL CHECK(amount_kobo>=0), currency TEXT NOT NULL DEFAULT 'NGN',
 provider_reference TEXT, status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_transactions_provider_reference ON transactions(provider_reference) WHERE provider_reference IS NOT NULL;
CREATE TABLE IF NOT EXISTS ledger_entries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ledger_account_id BIGINT NOT NULL REFERENCES ledger_accounts(id),
 transaction_id BIGINT NOT NULL REFERENCES transactions(id), direction TEXT NOT NULL CHECK(direction IN ('debit','credit')),
 amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT NOT NULL CHECK(amount_kobo>=0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(ledger_account_id,transaction_id,direction)
);
CREATE TABLE IF NOT EXISTS member_bank_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id), bank_code TEXT NOT NULL,
 bank_name TEXT NOT NULL, account_number TEXT NOT NULL, account_name TEXT NOT NULL, recipient_code TEXT, verified_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(member_id,bank_code,account_number)
);
CREATE TABLE IF NOT EXISTS withdrawal_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 ledger_account_id BIGINT NOT NULL REFERENCES ledger_accounts(id), amount NUMERIC(18,2) NOT NULL CHECK(amount>0),
 amount_kobo BIGINT NOT NULL CHECK(amount_kobo>0), bank_name TEXT, account_name TEXT, account_number TEXT,
 bank_account_id BIGINT REFERENCES member_bank_accounts(id), transfer_reference TEXT UNIQUE,
 provider_status TEXT NOT NULL DEFAULT 'not_started', status TEXT NOT NULL DEFAULT 'PENDING',
 reviewed_by BIGINT REFERENCES users(id), reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS consents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES member_applications(id),
 type TEXT NOT NULL, accepted INTEGER NOT NULL DEFAULT 0, accepted_at TIMESTAMPTZ, ip_address TEXT
);
CREATE TABLE IF NOT EXISTS kyc_checks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES member_applications(id),
 provider TEXT NOT NULL DEFAULT 'SANDBOX', session_ref TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'KYC_PENDING',
 raw_status_detail TEXT, verified_at TIMESTAMPTZ, attempt_count INTEGER NOT NULL DEFAULT 0, last_attempt_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS membership_payments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES member_applications(id),
 provider TEXT NOT NULL, reference TEXT NOT NULL UNIQUE, amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT,
 currency TEXT NOT NULL DEFAULT 'NGN', status TEXT NOT NULL DEFAULT 'PAYMENT_PENDING', verified_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS community_onboarding (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL UNIQUE REFERENCES members(id),
 whatsapp_joined INTEGER NOT NULL DEFAULT 0, orientation_completed INTEGER NOT NULL DEFAULT 0,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS contribution_plans (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT, frequency TEXT NOT NULL, purpose TEXT NOT NULL,
 target_amount NUMERIC(18,2), target_amount_kobo BIGINT, status TEXT NOT NULL DEFAULT 'PROPOSED',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS payment_identities (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 provider TEXT NOT NULL, identity_ref TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS receipts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaction_id BIGINT NOT NULL UNIQUE REFERENCES transactions(id),
 receipt_number TEXT NOT NULL UNIQUE, issued_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS webhook_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider TEXT NOT NULL, event_id TEXT NOT NULL,
 payload_json TEXT NOT NULL, processed INTEGER NOT NULL DEFAULT 0, received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(provider,event_id)
);
CREATE TABLE IF NOT EXISTS referrals (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES member_applications(id),
 referral_code TEXT, referred_by TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id BIGINT, action TEXT NOT NULL,
 entity_type TEXT NOT NULL, entity_id BIGINT, detail_json TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


CREATE TABLE IF NOT EXISTS opportunities (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, slug TEXT NOT NULL UNIQUE,
 headline TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'Business opportunity',
 public_summary TEXT NOT NULL, full_summary TEXT, why_it_matters TEXT,
 source_name TEXT NOT NULL, source_url TEXT NOT NULL, eligibility TEXT, deadline DATE,
 location TEXT DEFAULT 'Nigeria', funding_benefit TEXT, required_contribution TEXT,
 conditions TEXT, application_steps TEXT, documents_required TEXT, risks TEXT,
 fit_verdict TEXT, fit_score INTEGER CHECK(fit_score IS NULL OR (fit_score BETWEEN 0 AND 100)),
 next_action TEXT NOT NULL DEFAULT 'WATCH', status TEXT NOT NULL DEFAULT 'CONFIRMED',
 publication_status TEXT NOT NULL DEFAULT 'DRAFT', members_only INTEGER NOT NULL DEFAULT 1,
 featured INTEGER NOT NULL DEFAULT 0, published_at TIMESTAMPTZ,
 created_by BIGINT REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_opportunities_publication
ON opportunities(publication_status, status, deadline);
