-- Obit Cooperative PostgreSQL financial target schema
-- Integer kobo fields are authoritative for all money.

CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT UNIQUE, phone TEXT UNIQUE,
 password_hash TEXT, role TEXT NOT NULL DEFAULT 'member' CHECK(role IN ('member','staff','admin')),
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED','CLOSED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS member_applications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT REFERENCES users(id), full_legal_name TEXT,
 date_of_birth TEXT, gender TEXT, phone TEXT, whatsapp TEXT, email TEXT, address TEXT, state TEXT, lga TEXT,
 occupation_category TEXT, membership_type TEXT, application_date TIMESTAMPTZ NOT NULL DEFAULT now(),
 next_of_kin_name TEXT, next_of_kin_phone TEXT, intended_savings_amount NUMERIC(18,2),
 intended_savings_frequency TEXT, interests_json TEXT, referral_source TEXT, campaign TEXT,
 status TEXT NOT NULL DEFAULT 'LEAD', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS members (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL UNIQUE REFERENCES member_applications(id),
 user_id BIGINT REFERENCES users(id), member_code TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'ACTIVE',
 activated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ledger_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 account_type TEXT NOT NULL DEFAULT 'SAVINGS', balance NUMERIC(18,2) NOT NULL DEFAULT 0,
 balance_kobo BIGINT NOT NULL DEFAULT 0 CHECK(balance_kobo>=0), currency TEXT NOT NULL DEFAULT 'NGN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id), type TEXT NOT NULL,
 amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT NOT NULL CHECK(amount_kobo>=0), currency TEXT NOT NULL DEFAULT 'NGN',
 provider_reference TEXT, status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_transactions_provider_reference ON transactions(provider_reference) WHERE provider_reference IS NOT NULL;
CREATE TABLE IF NOT EXISTS ledger_entries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ledger_account_id BIGINT NOT NULL REFERENCES ledger_accounts(id),
 transaction_id BIGINT NOT NULL REFERENCES transactions(id), direction TEXT NOT NULL CHECK(direction IN ('debit','credit')),
 amount NUMERIC(18,2) NOT NULL, amount_kobo BIGINT NOT NULL CHECK(amount_kobo>=0), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(ledger_account_id,transaction_id,direction)
);
CREATE TABLE IF NOT EXISTS member_bank_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id), bank_code TEXT NOT NULL,
 bank_name TEXT NOT NULL, account_number TEXT NOT NULL, account_name TEXT NOT NULL, recipient_code TEXT, verified_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(member_id,bank_code,account_number)
);
CREATE TABLE IF NOT EXISTS withdrawal_requests (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, member_id BIGINT NOT NULL REFERENCES members(id),
 ledger_account_id BIGINT NOT NULL REFERENCES ledger_accounts(id), amount NUMERIC(18,2) NOT NULL CHECK(amount>0),
 amount_kobo BIGINT NOT NULL CHECK(amount_kobo>0), bank_name TEXT, account_name TEXT, account_number TEXT,
 bank_account_id BIGINT REFERENCES member_bank_accounts(id), transfer_reference TEXT UNIQUE,
 provider_status TEXT NOT NULL DEFAULT 'not_started', status TEXT NOT NULL DEFAULT 'PENDING',
 reviewed_by BIGINT REFERENCES users(id), reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
